{% set name = "cornice" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfd1b6c2a991a7ccb1b2082b6de9e3b8f198b6a2b4a07ab0800e05df05a45361

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - pyramid >=1.7,<3
    - venusian

test:
  imports:
    - cornice

about:
  home: https://github.com/Cornices/cornice
  summary: 'Cornice provides helpers to build & document Web Services with Pyramid.'
  description: |
    Cornice provides helpers to build & document REST-ish Web Services with Pyramid,
    with decent default behaviors. It takes care of following the HTTP specification
    in an automated way where possible. We designed and implemented cornice in a really
    simple way, so it is easy to use and you can get started in a matter of minutes.
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://cornice.readthedocs.io
  dev_url: https://github.com/Cornices/cornice

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
